### ISSUE TITLE
CSS Bug - Message input covers messages list

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-socketio-redis-chat-example#8]
when there are _enough_ messages to fill the screen, the input covers the last message(s):
<img width="851" alt="css-message-input-covers-messages-list" src="https://cloud.githubusercontent.com/assets/194400/8637116/bb575640-2879-11e5-9a31-bc9cbcf38533.png">

**Comment by iteles** [comment]
Linked to #21 as ensuring that the messages `ul` is scrolled all the way down to the bottom allows the extra bottom padding on the body to do its work of keeping things out from behind the message input `form` (as per this issue).
```css
body { 
  font: 1.5em Helvetica, Arial; 
  height: 100%; 
  padding-bottom: 2.3em;
  overflow:auto;
}
```
Also linked to #22.
